name: Build and Release Bundled Backend

on:
  push:
    tags:
      - 'v*'

jobs:
  build-bundled-releases:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [x64, arm64]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up variables
      id: vars
      run: |
        echo "NODE_VERSION=24.2.0" >> $GITHUB_OUTPUT
        echo "ARCH=${{ matrix.arch }}" >> $GITHUB_OUTPUT
        if [ "${{ matrix.arch }}" = "x64" ]; then
          echo "NODE_ARCH=x64" >> $GITHUB_OUTPUT
          echo "LINUX_ARCH=linux-x64" >> $GITHUB_OUTPUT
        else
          echo "NODE_ARCH=arm64" >> $GITHUB_OUTPUT  
          echo "LINUX_ARCH=linux-arm64" >> $GITHUB_OUTPUT
        fi
        
    - name: Download Node.js ${{ steps.vars.outputs.NODE_VERSION }}
      run: |
        echo "Downloading Node.js for ${{ steps.vars.outputs.LINUX_ARCH }}"
        wget https://nodejs.org/dist/v${{ steps.vars.outputs.NODE_VERSION }}/node-v${{ steps.vars.outputs.NODE_VERSION }}-${{ steps.vars.outputs.LINUX_ARCH }}.tar.xz
        tar -xf node-v${{ steps.vars.outputs.NODE_VERSION }}-${{ steps.vars.outputs.LINUX_ARCH }}.tar.xz
        mv node-v${{ steps.vars.outputs.NODE_VERSION }}-${{ steps.vars.outputs.LINUX_ARCH }} nodejs
        echo "Node.js extracted to nodejs/"
        
    - name: Install dependencies
      run: |
        echo "Installing backend dependencies..."
        export PATH="$PWD/nodejs/bin:$PATH"
        node --version
        npm --version
        npm install --production --no-optional
        echo "Dependencies installed successfully"
        
    - name: Create bundle directory
      run: |
        echo "Creating bundle directory..."
        mkdir -p karere-backend-bundle-${{ matrix.arch }}
        cp -r nodejs karere-backend-bundle-${{ matrix.arch }}/
        cp -r src karere-backend-bundle-${{ matrix.arch }}/
        cp -r node_modules karere-backend-bundle-${{ matrix.arch }}/
        cp package.json karere-backend-bundle-${{ matrix.arch }}/
        cp package-lock.json karere-backend-bundle-${{ matrix.arch }}/
        echo "Bundle directory created"
        
    - name: Create startup script
      run: |
        echo "Creating startup script..."
        cat > karere-backend-bundle-${{ matrix.arch }}/start-backend.sh << 'EOF'
        #!/bin/bash
        # Karere Backend Startup Script
        
        # Get the directory where this script is located
        SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        
        # Set up Node.js path
        export PATH="$SCRIPT_DIR/nodejs/bin:$PATH"
        
        # Set up working directory
        cd "$SCRIPT_DIR"
        
        # Start the backend
        exec node src/backend.js "$@"
        EOF
        chmod +x karere-backend-bundle-${{ matrix.arch }}/start-backend.sh
        echo "Startup script created"
        
    - name: Create README
      run: |
        echo "Creating README..."
        cat > karere-backend-bundle-${{ matrix.arch }}/README.md << 'EOF'
        # Karere Backend Bundle
        
        This bundle contains everything needed to run the Karere backend:
        - Node.js 24.2.0
        - Karere backend source code  
        - All required dependencies
        
        ## Usage
        
        ```bash
        # Make the startup script executable (if needed)
        chmod +x start-backend.sh
        
        # Run the backend
        ./start-backend.sh
        ```
        
        The backend will start on port 8765 by default.
        
        ## Architecture
        
        This bundle is built for: ${{ matrix.arch }}
        EOF
        echo "README created"
        
    - name: Create zip archive
      run: |
        echo "Creating zip archive..."
        zip -r karere-backend-bundle-${{ matrix.arch }}.zip karere-backend-bundle-${{ matrix.arch }}/
        ls -lh karere-backend-bundle-${{ matrix.arch }}.zip
        echo "Zip archive created"
        
    - name: Calculate checksums
      run: |
        echo "Calculating checksums..."
        sha256sum karere-backend-bundle-${{ matrix.arch }}.zip > karere-backend-bundle-${{ matrix.arch }}.zip.sha256
        echo "Checksum for ${{ matrix.arch }}:"
        cat karere-backend-bundle-${{ matrix.arch }}.zip.sha256
        
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          karere-backend-bundle-${{ matrix.arch }}.zip
          karere-backend-bundle-${{ matrix.arch }}.zip.sha256
        body: |
          ## Karere Backend Release
          
          This release includes bundled packages for multiple architectures:
          - Linux x64 (Intel/AMD 64-bit)
          - Linux ARM64 (ARM 64-bit)
          
          Each bundle contains:
          - Node.js 24.2.0 runtime
          - Karere backend source code
          - All required dependencies
          
          Download the appropriate bundle for your system and run:
          ```bash
          unzip karere-backend-bundle-*.zip
          cd karere-backend-bundle-*/
          ./start-backend.sh
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
