name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Linux x64 build
          - os: ubuntu-latest
            arch: x64
            node-version: '22'
            build-script: 'build:x64'
          # Linux ARM64 build
          - os: ubuntu-latest
            arch: arm64
            node-version: '22'
            build-script: 'build:arm64'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Bundle application
      run: npm run bundle

    - name: Build SEA executable
      run: npm run ${{ matrix.build-script }}

    - name: List dist directory (debug)
      run: ls -la dist/
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: karere-backend-linux-${{ matrix.arch }}
        path: dist/karere-backend-linux-${{ matrix.arch }}*
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: List artifacts (debug)
      run: find artifacts/ -type f -name "*" | head -20

    - name: Prepare release files
      run: |
        mkdir -p release/
        find artifacts/ -name "karere-backend-*" -type f -exec cp {} release/ \;
        ls -la release/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/*
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Karere Backend Release

          This release includes pre-built Linux binaries for multiple architectures:
          - Linux x64 (Intel/AMD 64-bit)
          - Linux ARM64 (ARM 64-bit)

          Download the appropriate binary for your system and make it executable:
          ```bash
          chmod +x karere-backend-linux-*
          ./karere-backend-linux-*
          ```

          These binaries are built using Node.js Single Executable Applications (SEA) and include all dependencies.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
