name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: node18-linux-x64
            name: linux-x64
          - target: node18-linux-arm64
            name: linux-arm64
          - target: node18-win-x64
            name: windows-x64
          - target: node18-macos-x64
            name: macos-x64
          - target: node18-macos-arm64
            name: macos-arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install pkg
      run: npm install -g pkg
      
    - name: Build executable
      run: pkg . --target ${{ matrix.target }} --output karere-backend-${{ matrix.name }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: karere-backend-${{ matrix.name }}
        path: karere-backend-${{ matrix.name }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          karere-backend-*/karere-backend-*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
